// INCLUDE FILE generated by "Pelles C for Windows, version 4.50".

#define IDI_MAIN          1000

#define IDM_MAIN          1100 // Menüpunkte
#define IDM_OPEN          1110 // Datei öffnen
#define IDM_SAVE          1120 // Datei speichern
#define IDM_SELECT        1200 // Auswahl
#define IDM_HELP          1300 // Hilfe
#define IDM_ENDE          1400 // Ende

#define IDC_TREE          1500 // Control TreeView
#define IDC_STBA          1600 // Control Status-Bar

#define IDR_RTFI          1700 // Returncode Textfeld
#define IDD_HELP          1800 // Hilfefenster
#define IDB_RTFI          1810 // RTF-Textfeld

#define IDD_SELECT        1900 // Auswahlfenster (rechteckig/kreisförmig)
#define IDC_SELECT_LAT    1910 // Editierfeld Latitude
#define IDC_SELECT_LON    1920 // Editierfeld Longitude
#define IDC_SELECT_SIZE   1930 // Editierfeld Größe
#define IDC_SELECT_CIRCLE 1940 // Radiobutton Kreis
#define IDC_SELECT_RECT   1950 // Radiobutton Rechteck
