// INCLUDE FILE generated by "Pelles C for Windows, version 4.50".

#define IDI_MAIN	1000

#define IDM_MAIN   	1100
#define IDM_OPEN   	1110
#define IDM_HELP   	1120
#define IDM_ENDE   	1130

#define IDC_TREE	1200

#define IDC_STBA	1300

#define IDR_RTFI	1400

#define IDD_HELP	1500
#define IDB_RTFI	1510
